[build]
  command = "CI=false npm run build --workspace=client"
  publish = "client/dist"

[context.production.environment]
  VITE_API_URL = "https://torneobjjbackend.up.railway.app/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
